services:
  my-app:
    image: fxdealprocessor:1.0
    environment:
      CONNECTION_STRING: jdbc:mysql://localhost:3306/my_database
      DB_USER: root
      DB_PASSWORD: Basel@1234
    ports:
      - "8080:80"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Basel@1234
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"
    volumes:
      - mysql-datastore:/var/lib/mysql
volumes:
  mysql-datastore:
